### ISSUE TITLE
Change directory of masscan binary from /usr/bin to /usr/local/bin

### ISSUE THREAD

**Issue by opsdisk** [opsdisk/scantron#5]
https://github.com/opsdisk/scantron/blob/175f93c501780f09befb7127028a141b1e5a1b3f/ansible-playbooks/roles/engine/tasks/main.yml#L37

**Comment by RishiKumarRay** [comment]
hey can you please review the PR #6  for this issue

**Comment by RishiKumarRay** [comment]
@opsdisk please do the review

**Comment by RishiKumarRay** [comment]
@opsdisk Hey , Can you add my name to contributors list please?
